### ISSUE TITLE
Can not attach SnappingSheetController

### ISSUE THREAD

**Issue by maitycyrus** [AdamJonsson/snapping_sheet#63]
I always get the error:

```
SnappingSheet must be attached before calling any function from the controller. Pass in the controller to the snapping sheet widget to attached. Use [isAttached] to check if it is attached or not.
'package:snapping_sheet/src/snapping_sheet_widget.dart':
Failed assertion: line 418 pos 7: 'isAttached'
```
Also, I think there is a mistake in your readme of how to attach the SnappingSheetController. You call the constructor of the controller twice. I tried it both way, and it did not work.

**Comment by redmacdev1988** [comment]
I have the code set up like the example and I got the same error maitycyrus mentioned: 
"SnappingSheet must be attached before calling any function  from the controller". 

 I readjusted my code where I then

1)  create the SnappingSheetController()
2) create the SnappingSheet, and attach the controller

`
 @override
  void initState() {

    _snappingSheetController = SnappingSheetController();

    this.sheet = SnappingSheet(
      controller: _snappingSheetController, // snappingSheetController attached here
      snappingPositions: [
        SnappingPosition.factor(
          positionFactor: POSITION_FACTOR_START,
...
...
}`

Now I"m getting a Null check operator on a null value error:

[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      _SnappingSheetState.sheetSize
package:snapping_sheet/src/snapping_sheet_widget.dart:307
#1      _SnappingSheetState.initState.<anonymous closure>.<anonymous closure>
package:snapping_sheet/src/snapping_sheet_widget.dart:192
#2      State.setState
package:flutter/…/widgets/framework.dart:1267
#3      _SnappingSheetState.initState.<anonymous closure>
package:snapping_sheet/src/snapping_sheet_widget.dart:190
#4      _rootRunUnary (dart:async/zone.dart:1362:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#9      Future._complete (dart:async/future_impl.dart:530:7)
#10     new Future.delayed.<anonymous closure> (dart:async/future.<…>

**Comment by AdamJonsson** [comment]
@maitycyrus You are right regarding the fault in the README, you should pass in the variable instead of creating a new controller. If you got the time, could you send the code for when you are using the controller?

@redmacdev1988 Seems that I can not replicate the error. Could you send the code for the entire widget that contains the SnappingSheet widget and uses the controller?

**Comment by maitycyrus** [comment]
`import 'package:flutter/material.dart';
import 'package:snapping_sheet/snapping_sheet.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.

    SnappingSheetController snappingSheetController = SnappingSheetController();
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: SnappingSheet(
        // Connect it to the SnappingSheet
        controller: snappingSheetController,

        grabbingHeight: 200,
        grabbing: GestureDetector(
          onTap: (){
            print('Controller is not working!');
            snappingSheetController.snapToPosition(
              SnappingPosition.factor(positionFactor: 0.75),
            );
          },
          child: Container(
            height: 200,
              color: Colors.blue
          ),
        ),
        sheetBelow: SnappingSheetContent(
          draggable: true,
          child: Container(color: Colors.red),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by maitycyrus** [comment]
import 'package:flutter/material.dart';
import 'package:snapping_sheet/snapping_sheet.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  @override
  Widget build(BuildContext context) {

    SnappingSheetController snappingSheetController = SnappingSheetController();
    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: SnappingSheet(
        // Connect it to the SnappingSheet
        controller: snappingSheetController,

        grabbingHeight: 200,
        grabbing: GestureDetector(
          onTap: (){
            print('Controller is not working!');
            snappingSheetController.snapToPosition(
              SnappingPosition.factor(positionFactor: 0.75),
            );
          },
          child: Container(
            height: 200,
              color: Colors.blue
          ),
        ),
        sheetBelow: SnappingSheetContent(
          draggable: true,
          child: Container(color: Colors.red),
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by maitycyrus** [comment]
> import 'package:flutter/material.dart';
> import 'package:snapping_sheet/snapping_sheet.dart';
> 
> void main() {
> runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
> // This widget is the root of your application.
> @override
> Widget build(BuildContext context) {
> return MaterialApp(
> title: 'Flutter Demo',
> theme: ThemeData(
> 
> ```
>     primarySwatch: Colors.blue,
>   ),
>   home: MyHomePage(title: 'Flutter Demo Home Page'),
> );
> ```
> 
> }
> }
> 
> class MyHomePage extends StatefulWidget {
> MyHomePage({Key? key, required this.title}) : super(key: key);
> 
> final String title;
> 
> @override
> _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State {
> 
> @override
> Widget build(BuildContext context) {
> 
> ```
> SnappingSheetController snappingSheetController = SnappingSheetController();
> return Scaffold(
>   appBar: AppBar(
> 
>     title: Text(widget.title),
>   ),
>   body: SnappingSheet(
>     // Connect it to the SnappingSheet
>     controller: snappingSheetController,
> 
>     grabbingHeight: 200,
>     grabbing: GestureDetector(
>       onTap: (){
>         print('Controller is not working!');
>         snappingSheetController.snapToPosition(
>           SnappingPosition.factor(positionFactor: 0.75),
>         );
>       },
>       child: Container(
>         height: 200,
>           color: Colors.blue
>       ),
>     ),
>     sheetBelow: SnappingSheetContent(
>       draggable: true,
>       child: Container(color: Colors.red),
>     ),
>   ), // This trailing comma makes auto-formatting nicer for build methods.
> );
> ```
> 
> }
> }

Here is a minimal code sample reproducing the bug

**Comment by maitycyrus** [comment]
... code reproducing the bug

**Comment by Lix-ai** [comment]
Same error, same everything

**Comment by maitycyrus** [comment]
I think the problem is the initState method in _SnappingSheetState it does not get called when hot reloading. It works if I run on restart.

**Comment by akbarpulatov** [comment]
Can you check my PR #74? I checked with the example above, everything is working fine now.
